import config
import src.llm.google_gemini as llm

# Initialize the Gemini model for summarization
model = llm.Gemini(config.SUMMARY_MODEL)

def summarize_movie_text(row):
    """
    Summarizes movie information using a language model.

    This function takes movie information as input and generates a comprehensive,
    informative, and objective summary of the movie using the Gemini language model.
    The summaries are designed to be used for building a FAISS vector database
    for a movie recommendation system.

    Args:
        row (dict): A dictionary containing movie information to be summarized.

    Returns:
        str: A summary of the movie generated by the language model.
    """
    global model
    
    prompt = f"""
    You are a movie summarization engine. Your task is to create comprehensive, informative, and objective summaries of movies. These summaries will be used to build a FAISS vector database for a movie recommendation system. The system will match user queries to these summaries to find relevant movies.

    **Context:**

    *   The system recommends movies based on user queries.
    *   The database will contain thousands of movies.
    *   Summaries should be detailed enough for accurate retrieval, providing a thorough overview of the plot, setting, and key themes.

    **Example User Queries:** (These are examples; focus on writing a general-purpose summary)

    1.  "I'm looking for a lighthearted comedy to watch with friends.  Something with witty banter, but not slapstick."
    2.  "I want an epic fantasy movie with a strong female lead. Think quests and magic, but not too dark."
    3.  "I'm in the mood for a sci-fi thriller with a complex plot and twists, but not confusing."
    4.  "I'd like a historical drama set in the 18th century about political intrigue, but no war movies."
    5.  "Give me a good old-fashioned action movie. Lots of explosions and a hero who can take a beating."
    6.  "I'm looking for a comedy to relax with. I love buddy comedies, but I'm not into overly serious movies."
    7.  "I’m into epic desert adventures with a lot of action. I love movies that explore deep prophecies and hero journeys."

    **Movie Information:**

    {str(row)}

    **Instructions:**

    Write a single paragraph summarizing the movie.  This paragraph should be:

    *   **Objective:** Describe the movie's genre(s), setting (time and place), core themes, and *key* plot elements.  Mention prominent character *types* (e.g., "reluctant hero," "wise mentor"), not detailed personalities.  Be specific with genres (e.g., "Sci-Fi Thriller," not just "Sci-Fi"). DO NOT use the name of the movie and too many stopwords.
    *   **Comprehensive and Informative:** Capture the essence of the movie in a way that distinguishes it from others.  Include enough detail to be useful for retrieval. The summary should thoroughly cover the plot, setting, and main themes.
    *   **Plain, Unstructured Text:**  Write a single, continuous paragraph. Do *not* use bullet points, headings, lists, or any other formatting.  Just plain text.
    *   **No Opinions:** Avoid subjective language ("amazing," "terrible"). Focus on facts.
    *   **Do NOT make the summary too short.**  It should provide sufficient detail for accurate movie recommendations.
    *  **The summary should be at least 100 words long.**
    * "Do not simply list keywords; write a flowing narrative."
    """

    
    print("Prompting LLM...")

    # Generate the response using the Gemini model
    return model.generate_response(prompt, max_output_tokens=200, temperature=0.7)
